let MilkshakeJson = [
    { id: 1, name: 'Abacaxi', img: 'img/Milkshakes/milk-abacaxi.png', price: [14.00, 17.00, 19.00], sizes: ['300', '400', '500'], description: 'Perfeita combinação entre a refrescância do abacaxi e cremosidade do leite' },
    { id: 2, name: 'Abacaxi com hortelã', img: 'img/Milkshakes/milk-abacaxi-com-hortela.png', price: [15.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'Perfeita combinação entre a refrescância do abacaxi e a cremosidade do leite e um toque de hortelã.' },
    { id: 3, name: 'Banana com chocolate', img: 'img/Milkshakes/milk-banana-com-chocolate.png', price: [14.00, 16.00, 18.00], sizes: ['300', '400', '500'], description: 'Sabor surpreendente de banana com pedaços de chocolate' },
    { id: 4, name: 'Brigadeiro', img: 'img/Milkshakes/milk-brigadeiro.png', price: [16.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'O delicioso sabor do docinho mais famoso do Brasil' },
    { id: 5, name: 'Ceú azul', img: 'img/Milkshakes/milk-ceu-azul.png', price: [14.00, 16.00, 17.00], sizes: ['300', '400', '500'], description: 'Sabor de nata, docinho, refrescante e com a divertida cor azul' },
    { id: 6, name: 'Chantilícia banoffe', img: 'img/Milkshakes/milk-chantilicia-banoffe.png', price: [17.00, 19.00, 20.00], sizes: ['300', '400', '500'], description: 'Milk Shake sabor Doce de Leite com pedaços de Banana e Crocantes pedacinhos de Biscoito Maria. Finalizado com um Topo delicioso de Chantilly e Cobertura de Chocolate' },
    { id: 7, name: 'Chantilícia bombom de morango', img: 'img/Milkshakes/milk-chantilicia-bombom-de-morango.png', price: [19.00, 21.00, 23.00], sizes: ['300', '400', '500'], description: 'Milk Shake de Morango com pedacinhos de Chocolate, trufado com Creme de Avelã. Cobertura de Chantilly com toque de chocolate em pó e calda de Polpa de Morango' },
    { id: 8, name: 'Chantilícia de brigadeiro trufado', img: 'img/Milkshakes/milk-chantilicia-brigadeiro-trufado.png', price: [20.00, 22.00, 25.00], sizes: ['300', '400', '500'], description: 'Milk Shake de Brigadeiro com pedaços de chocolate, trufado com Creme de Avelã. Cobertura de Chantilly, Granulado e calda de Chocolate Nestlé®' },
    { id: 9, name: 'Chantilícia de pave de maracujá', img: 'img/Milkshakes/milk-chantilicia-pave-de-maracuja.png', price: [17.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'Milkshake sabor Maracujá, Trufado com creme de Avelã. Finalizado com um topo delicioso de chantily, cobertura de chocolate e uma calda cremosa de maracujá' },
    { id: 10, name: 'Chiclete', img: 'img/Milkshakes/milk-chiclete.png', price: [14.00, 15.00, 16.00], sizes: ['300', '400', '500'], description: 'Delicioso gostinho de chiclete' },
    { id: 11, name: 'Chocolate', img: 'img/Milkshakes/milk-chocolate.png', price: [16.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'Um clássico, sempre entre os mais pedidos' },
    { id: 12, name: 'Chocolate Branco', img: 'img/Milkshakes/milk-chocolate-branco.png', price: [15.00, 17.00, 19.00], sizes: ['300', '400', '500'], description: 'Creme e delicioso' },
    { id: 13, name: 'Chocolate com ovomaltine', img: 'img/Milkshakes/milk-ovomaltine.png', price: [18.00, 20.00, 22.00], sizes: ['300', '400', '500'], description: 'Sabor chocolate com flocos crocantes de Ovomaltine' },
    { id: 14, name: 'Chocolate Duo', img: 'img/Milkshakes/milk-chocolate-duo.png', price: [17.00, 19.00, 21.00], sizes: ['300', '400', '500'], description: 'Combinação irresistível do chocolate branco com pedaços de chocolate ao leite' },
    { id: 15, name: 'Chocomenta', img: 'img/Milkshakes/milk-chocomenta.png', price: [21.00, 22.00, 24.00], sizes: ['300', '400', '500'], description: 'A refrescância da menta com pedacinhos crocantes de chocolate' },
    { id: 16, name: 'Coco branco', img: 'img/Milkshakes/milk-coco-branco.png', price: [14.00, 16.00, 18.00], sizes: ['300', '400', '500'], description: 'Cremoso milk shake de coco com pedacinhos da fruta' },
    { id: 17, name: 'Flocos', img: 'img/Milkshakes/milk-flocos.png', price: [15.00, 17.00, 19.00], sizes: ['300', '400', '500'], description: 'Sabor de creme com pedaços de chocolate ao leite e granulado' },
    {
        id: 18, name: 'Floresta negra', img: 'img/Milkshakes/milk-floresta-negra.png', price: [17.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'Milk shake de chocolate, mais cereja e pedacinhos de chocolate'
    },
    { id: 19, name: 'Iogurte com amora', img: 'img/Milkshakes/milk-iogurte-com-amora.png', price: [15.00, 16.00, 18, 00], sizes: ['300', '400', '500'], description: 'O sabor do Iogurte com deliciosa de polpa de amora' },
    { id: 20, name: 'Leite condensado ', img: 'img/Milkshakes/milk-leite-condensado.png', price: [16.00, 18.00, 20.00], sizes: ['300', '400', '500'], description: 'Uma delícia que dispensa apresentações' }
]   